### ISSUE TITLE
Build for whonix-gateway-cli produces incorrect UTM config file

### ISSUE THREAD

**Issue by derbbre** [derivative-maker/derivative-maker#9]
This is Whonix specific but I couldn't find a way to report it there. If I build with 
`./derivative-maker --flavor whonix-gateway-cli --target utm --arch arm64 --repo true`
on Apple Silicon (Mac Studio M1) everything comes out fine except the resulting property list for UTM (config.plist) includes an error, listing 'Whonix-Gateway-XFCE.raw' in the Drives key instead of the resulting 'Whonix-Gateway-CLI.raw'. 

To repeat, the image filename is correct within the package but the resulting plist has an incorrect entry, resulting in a UTM error as it can't find that image. Simple enough fix to change the plist – the VM seems to work fine otherwise.

I poked around the code but couldn't find where this key is created, please let me know if I can help with testing.

**Comment by adrelanos** [comment]
At time of writing it entirely unsupported.

https://www.whonix.org/wiki/Unsupported

(non-)progress here:

https://forums.whonix.org/t/whonix-on-mac-m1-arm-user-support-still-unsupported-at-time-of-writing/11310
